<?php

/**
 * @file
 * Primary module hooks for My users module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_theme().
 */
function my_users_theme($existing, $type, $theme, $path) {
  return array('modal' =>                  // this is the name of the template
    array(
      'variables' => array(
        'title' => 'Default title',
        'description' => null,
        'id' => null,
      ),
    )
  );
}